### PR TITLE
Nsato caf support

### PR DESCRIPTION
**Pull request by necrosato**

### CODE REVIEW

**Comment by zbeekman** [comment]
LGTM

**Comment by zbeekman** [comment]
Just to confirm, this is for supporting OpenCoarrays? Or are there other caf compilers with similar syntax that we are supporting?

**Comment by zbeekman** [comment]
Also, should I have Travis install OpenCoarrays so that the CI test can test this?

**Comment by nchaimov** [comment]
Yes, this is just for OpenCoarrays. If you have the chance, yes, installing OpenCoarrays on Travis would be useful.

**Comment by zbeekman** [comment]
So, to do that it looks like most likely I will have to

1) upgrade to a newer GCC/GFortran
2) Install MPI (which is good because, it will exercise more tests)
3) install OpenCoarrays

Of these 3 steps only step 2 will be time consuming (installing MPI) but we may be able to implement some logic to cache the installation. If this has been tested locally then I vote we merge this before implementing the travis updates.

Right now tests take ~15 minutes. Depending on how long the MPI and caf tests take, there should be plenty of time to install MPI etc.

I wonder if I can just install binaries for both with conda.

**Comment by nchaimov** [comment]
Source-inst isn't allowed because TAU itself doesn't support source instrumentation of Coarray Fortran code. The tau_caf.sh wrapper script will force -optCompInst on regardless of whether it is set.

**Comment by zbeekman** [comment]
oh, nm the bit about the warning. This is just due to baseline being the only measurement, since I'm on macOS and there's no binutils support.

**Comment by zbeekman** [comment]
ah I see. I'm curious why tau itself is disallowing source inst. Is it just because of a lack of parser support?

**Comment by nchaimov** [comment]
Yes, no parser support.

**Comment by zbeekman** [comment]
I sort of doubt whether the parser support *really* matters. OpenCoarrays
is built on MPI and as long as the parser can find procedures and insert
profiler declarations and timer start/stop calls it should be ok. I guess
one question is whether the parsers explode when they see coarrays, but
GFortran 7.1 has perfectly good coarray support so a parser based on that
should be fine.

**Comment by sameershende** [comment]
Hi Zaak,
	The gfortran parser explodes as soon as it sees CoArray syntax in the code. So, -optCompInst is the only option for now. We don’t send it to the PDT Gfortran 4.8.5 parser using gfparse48. Once we implement support for Gfortran 7.3 in PDT, we can reenable this functionality. Until then, we can only rely on compiler-based instrumentation when tau_caf.sh  is invoked. You can always call tau_f90.sh which will enable parser support. 
	Thanks,
	- Sameer

**Comment by zbeekman** [comment]
Hi Sameer,

Ok, thanks for the update! Does the GFortran 7.1 based parser explode? I
*think* that's what I've been using (via gfparse) and after making some
tweaks to some of the tau and pdt shell scripts it seems fairly robust. At
a later date, I'll try an experiment with source based instrumentation of a
coarray program to investigate what's going wrong and see if I can coax the
parser into inserting useful instrumentation.

Thanks,
Zaak

**Comment by sameershende** [comment]
Hi Zaak,
	There is no gfortran 7.1 based parser in PDT right now to test this. We have only gfortran 4.8.5 in PDT. For source instrumentation, we rely on PDT’s parsing capabilities. So, there is no way to support CoArray codes with source instrumentation at present. It will require a lot of effort to implement this - it is a separate project in its own right. Please don’t waste your time trying to source instrument CoArray codes at present. Compiler-based instrumentation coupled with EBS is sufficient for now. 
	Thanks,
	- Sameer

**Comment by zbeekman** [comment]
Yes, I agree, I'm not going to work on this.

**Pull request merged**
